### ISSUE TITLE
Vampirism 1.10 causes all Village Iron Golems to be hostile

### ISSUE THREAD

**Issue by JDtheHutt** [KooriKitsune38/Vampirism-Datapack#1]
I have only tested Vampirism v1.10, however this has the same result on Minecraft vanilla 1.18.1 and Fabric 1.18.1 with modloader 0.13.2.

Issue:
All Iron Golems in Villages are permanently and globally hostile to all players as soon as the datapack is added, and without completing any of the Vampirism content.  This includes those in villages not yet generated in unvisited chunks.  Removing the datapack has no effect, all players remain affected.  Attempts to raise village reputation have no effect, all Iron Golems remain hostile.  Using commands to kill all Village Golems and allowing them to respawn does not resolve this either, the new ones remain hostile.  This affects both singleplayer worlds and multiplayer servers.

Steps to reproduce:
Start a new world in 1.18.1 and add the Vampirism v1.10 datapack.  Do not do any Vampirism content and instead immediately visit a village, and Iron Golems immediately will begin attacking.  Remove the datapack, and reload, and the attacks continue.  Restart the entire client or server, and the attacks continue.  Visit other villages in not yet generated chunks that you have never been to, and they also attack.

Player built Golems remain passive, and do not attack.

Any advice on how to resolve this would be very appreciated please, as it's busted my survival server due to noone being able to set foot in any place where Iron Golems reside.  If I can provide any other information, please let me know.

**Comment by JDtheHutt** [comment]
Actually, think I do have a fix.  I forgot that I did a chunk generation earlier tonight, so while I hadn't visited the areas, they certainly had been chunk generated.  Deleting the entities folder obviously murders all the entities but it does remove the aggression of the generated golems.

**Comment by KooriKitsune38** [comment]
I fixed the problem.
It was due to the data command not including the predicate for checking vampires/bats so it took the UUID from every entity nearby instead.
